services:
  opa:
    image: openpolicyagent/opa:latest
    platform: linux/amd64
    ports:
      - '8181:8181'
    volumes:
      - ./policies:/policies
    command:
      - 'run'
      - '--server'
      - '--addr=0.0.0.0:8181'
      - '--set=decision_logs.console=true'
      - '/policies'
